### ISSUE TITLE
Problem computing?

### ISSUE THREAD

**Issue by J-A16** [cisc3620/5-lighting#3]
I put the equations in the fragment source and without even actually passing the results to the result vec3, the spinning box no longer renders. I guess the system is having trouble doing the calculations? As long as the equations are right, will I get full credit?

**Comment by J-A16** [comment]
@rivlev

**Comment by rivlev** [comment]
You probably have a syntax error in the shader

**Comment by J-A16** [comment]
I don't see any syntax errors though.

**Comment by J-A16** [comment]
@rivlev here is my fragmentSource, there are no syntax errors:

const GLchar* fragmentSource =
"#version 330 core\n"
"in vec3 Normal;"
"in vec3 FragPos;"

"uniform vec3 lightPos;"
"uniform vec3 viewPos;"
"uniform vec3 lightColor;"
"uniform vec3 objectColor;"

"out vec4 outColor;"
"void main()"
"{"
"    vec3 norm = normalize(Normal);"
"    vec3 lightDir = normalize(lightPos - FragPos);"
"    float diff = max(dot(norm, lightDir), 0.0);"
"    vec3 diffuse = diff * lightColor;"

"    vec3 ambient = vec3(0.2f,0.2f,0.2f);"
"    vec3 reflection = (2 * norm * dot(norm, lightDir)) - lightDir;"
"    vec3 eyeDir = normalize(viewPos - FragPos);"
"    float spec = max(dot(eyeDir, reflection), 0.0);"
"    vec3 specular = lightColor * spec^8;"

"    vec3 result = ((diffuse + ambient) * objectColor) + specular;"
"    outColor = vec4(result, 1.0);"
"}";

**Comment by rivlev** [comment]
set outcolor to constant, comment out all lines and uncomment line by line as long as it still works. make sure in your application you have all names matched up correctly

**Comment by jelmani** [comment]
On this line: 
" vec3 specular = lightColor * spec^8;"

Don't use the ^ symbol, use the pow function: pow(spec, 8)

**Comment by J-A16** [comment]
Thanks, forgot about that.
