### ISSUE TITLE
Extra credit 

### ISSUE THREAD

**Issue by TarekCodes** [cisc3620/5-lighting#4]
I'm not sure what we're supposed to do for extra credit portion. Do we need to draw all the normals or just calculate them and then store them somewhere? Thanks. @rivlev

**Comment by rivlev** [comment]
suppose you have a cube with 8 vertices
create an array with 8 * (3+3) floats for each vertex's position (x, y, z) and normal (x, y, z)
each normal (which you can calculate manually) should be the average of the normals to the three planes shared by the vertex 
then create an array with 3*2*6=36 ints indexing into that array (element buffer) 

send the positions and normals to the shaders as before. normalize normals in the shader.
